{{- $secretName := "mongo-secret" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: mongo
type: Opaque
data:
  rootPassword: {{ include "common.secrets.set" (dict
    "secret" $secretName
    "key" "rootPassword"
    "default" .Values.mongo.defaultSecret.rootPassword
    "context" $)
  }}
