apiVersion: v1
kind: Service
metadata:
  name: mongo-headless
  labels:
    {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: mongo
spec:
  clusterIP: None
  ports:
    - name: mongo
      port: 27017
  selector:
    {{- include "common.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: mongo
