apiVersion: v1
kind: Service
metadata:
  name: proxy
  labels:
    {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: proxy
spec:
  type: ClusterIP
  selector:
    {{- include "common.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: proxy
  ports:
    - name: proxy
      protocol: TCP
      port: 80
      targetPort: 80
