---
- hosts: ubuntu
  gather_facts: False
  environment:
    LC_ALL: en_US.UTF-8
  become: yes
  roles:
    - node
    - jupyter
    - containers
    - update
    - aa_demo


- hosts: rhel
  gather_facts: False
  environment:
    LC_ALL: en_US.UTF-8
  become: yes
  roles:
    - rhel_node

