{{- if ne .Values.node.type "gateway"}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: seaweedfs
  labels:
    {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: seaweedfs
spec:
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      {{- include "common.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: seaweedfs
  serviceName: seaweedfs
  podManagementPolicy: OrderedReady
  template:
    metadata:
      labels:
        {{- include "common.labels" . | nindent 8 }}
        app.kubernetes.io/component: seaweedfs
        {{- if .Values.seaweedfs.podLabels }}
        {{- toYaml .Values.seaweedfs.podLabels | nindent 8 }}
        {{- end }}
      {{- if .Values.seaweedfs.podAnnotations }}
      annotations: {{- toYaml .Values.seaweedfs.podAnnotations | nindent 8 }}
      {{- end }}
    spec:
      {{- if .Values.seaweedfs.nodeSelector }}
      nodeSelector: {{- .Values.seaweedfs.nodeSelector | toYaml | nindent 8 }}
      {{- end }}
      containers:
        - name: seaweedfs-container
          image: {{ .Values.global.registry }}/openmined/grid-seaweedfs:{{ .Values.global.version }}
          imagePullPolicy: Always
          resources: {{ include "common.resources.set" (dict "resources" .Values.seaweedfs.resources "preset" .Values.seaweedfs.resourcesPreset) | nindent 12 }}
          env:
            - name: SWFS_VOLUME_SIZE_LIMIT_MB
              value: {{ .Values.seaweedfs.master.volumeSizeMB | quote }}
            - name: S3_ROOT_USER
              value: {{ .Values.seaweedfs.s3.rootUser | quote }}
            - name: S3_ROOT_PWD
              valueFrom:
                secretKeyRef:
                    name: {{ .Values.seaweedfs.secretKeyName | required "seaweedfs.secretKeyName is required" }}
                    key: s3RootPassword
            {{- if .Values.seaweedfs.env }}
            {{- toYaml .Values.seaweedfs.env | nindent 12 }}
            {{- end }}
          ports:
            - name: mount-api-port
              containerPort: 4001
            - name: master-port
              containerPort: 9333
          startupProbe:
            httpGet:
              path: /?probe=startupProbe
              port: mount-api-port
            failureThreshold: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /cluster/healthz?probe=livenessProbe
              port: master-port
            periodSeconds: 60
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe: null
          volumeMounts:
            # master + filer + volume data
            - mountPath: /data/
              name: seaweedfs-data
              readOnly: false

            {{- if .Values.seaweedfs.filer.config }}
            # filer conf in $HOME/.seaweedfs/
            - mountPath: /root/.seaweedfs/filer.toml
              subPath: filer.toml
              name: seaweedfs-config
              readOnly: true
            {{- end }}

            {{- if .Values.seaweedfs.master.config }}
            # filer conf in $HOME/.seaweedfs/
            - mountPath: /root/.seaweedfs/master.toml
              subPath: master.toml
              name: seaweedfs-config
              readOnly: true
            {{- end }}

            {{- if .Values.seaweedfs.mountApi.mounts }}
            # automount config
            - mountPath: /root/swfs/automount.yaml
              subPath: automount.yaml
              name: seaweedfs-config
              readOnly: true
            {{- end }}

            {{- if .Values.seaweedfs.secret.mountCredentials }}
            # mount credentials to /run/secrets/
            {{- range $obj := $.Values.seaweedfs.secret.mountCredentials }}
            - mountPath: /run/secrets/{{ $obj.name }}
              subPath: {{ $obj.name }}
              name: seaweedfs-mount-creds
              readOnly: true
            {{- end }}
            {{- end}}

            {{- if .Values.seaweedfs.volumeMounts }}
            {{- toYaml .Values.seaweedfs.volumeMounts | nindent 12 }}
            {{- end }}
      terminationGracePeriodSeconds: 5
      volumes:
        - name: seaweedfs-config
          configMap:
            name: seaweedfs-config

        {{- if .Values.seaweedfs.secret.mountCredentials }}
        # mount secret as volume
        - name: seaweedfs-mount-creds
          secret:
            secretName: seaweedfs-mount-secret
        {{- end }}

        {{- if .Values.seaweedfs.volumes }}
        # custom volumes
        {{- toYaml .Values.seaweedfs.volumes | nindent 8 }}
        {{- end }}
  volumeClaimTemplates:
  - metadata:
      name: seaweedfs-data
      labels:
        {{- include "common.volumeLabels" . | nindent 8 }}
        app.kubernetes.io/component: seaweedfs
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: {{ .Values.seaweedfs.storageSize | quote }}
{{ end }}
