{{- if ne .Values.node.type "gateway"}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: seaweedfs-config
  labels:
    {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: seaweedfs
data:
  filer.toml: |
    [leveldb2]
    enabled = true
    dir = "./filerldb2"
  start.sh: |
    #! /usr/bin/env bash

    sleep 30 &&
    echo "s3.configure -access_key ${S3_ROOT_USER} -secret_key ${S3_ROOT_PWD} -user iam -actions Read,Write,List,Tagging,Admin -apply" \
    | weed shell > /dev/null 2>&1 \
    & weed server -s3 -s3.port=${S3_PORT} -master.volumeSizeLimitMB=${S3_VOLUME_SIZE_MB}
{{ end }}
