{{- if and (ne .Values.node.type "gateway") (.Values.seaweedfs.secret.mountCredentials) }}
{{- $secretName := "seaweedfs-mount-secret" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: seaweedfs
type: Opaque
data:
  # we don't need to call "common.secrets.set" because:
  # 1. secrets are not generated randomly
  # 2. secrets can expire and might require a force update
  {{- range $obj := $.Values.seaweedfs.secret.mountCredentials }}
  {{ $obj.name }}: {{ $obj.value | b64enc }}
  {{- end }}
{{ end }}
