#Ansible process for podman setup

- name: Enable container-tools module
  shell: dnf module enable -y container-tools:rhel8
  tags: podman

- name: Install podman
  package:
    name: podman
    state: present
  tags: podman

- name: Install podman-docker
  package:
    name: podman-docker
    state: present
  tags: podman

- name: Start podman socket
  service:
    name: podman.socket
    state: started
    enabled: yes
  tags: podman

- name: Start podman service
  service:
    name: podman
    state: started
    enabled: yes
  tags: podman


