- name: Install required packages for building Python
    dnf:
      name:
        - gcc
        - openssl-devel
        - bzip2-devel
        - libffi-devel
        - zlib-devel
        - make
        - wget
      state: present

- name: Download Python 3.10.11 source code
      get_url:
        url: https://www.python.org/ftp/python/3.10.11/Python-3.10.11.tgz
        dest: /tmp/Python-3.10.11.tgz
        mode: '0644'

- name: Extract Python 3.10.11 source code
  unarchive:
    src: /tmp/Python-3.10.11.tgz
    dest: /tmp/
    remote_src: yes

- name: Configure Python 3.10.11 build
  command: ./configure --enable-optimizations --prefix=/usr/local
  args:
    chdir: /tmp/Python-3.10.11/

- name: Build Python 3.10.11
  command: make
  args:
    chdir: /tmp/Python-3.10.11/

- name: Install Python 3.10.11
  command: make altinstall
  args:
    chdir: /tmp/Python-3.10.11/

- name: Create a symlink for Python 3.10.11
  file:
    src: /usr/local/bin/python3.10
    dest: /usr/bin/python3.10
    state: link

- name: Cleanup downloaded source files
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /tmp/Python-3.10.11.tgz
    - /tmp/Python-3.10.11