---
- name: Register RHEL
  redhat_subscription:
    state: present
    username: "{{ rhel_subscription_username }}"
    password: "{{ rhel_subscription_password }}"
    auto_attach: true
  become: true
