global:
  # Affects only backend, frontend, and seaweedfs containers
  registry: docker.io
  version: 0.8.7-beta.1

  # Force default secret values for development. DO NOT SET THIS TO FALSE IN PRODUCTION
  randomizedSecrets: true

mongo:
  # MongoDB config
  port: 27017
  username: root

  # Extra environment vars
  env: null

  # Pod Resource Limits
  resourcesPreset: nano
  resources: null

  # PVC storage size
  storageSize: 5Gi

  # Mongo secret name. Override this if you want to use a self-managed secret.
  secretKeyName: mongo-secret

  # custom secret values
  secret:
    rootPassword: null

frontend:
  # Extra environment vars
  env: null

  # Pod Resource Limits
  resourcesPreset: micro
  resources: null

seaweedfs:
  # Master
  master:
    # Seaweed Volume Size in MB set on master. This is not PVC.
    volumeSizeMB: 1000
    # master.toml For details check weed scaffold -config=master
    config: null

  # filer
  filer:
    # filer.toml For details check weed scaffold -config=filer
    config: null

  # S3
  s3:
    rootUser: admin

  # Mount API
  mountApi:
    port: 4001

    # automount:
    #   - local_bucket: test-bucket
    #     remote_bucket:
    #       type: gcs
    #       bucket_name: test-bucket
    #       creds: /etc/secrets/gcs_creds.json
    automount: null

  # Extra environment vars
  env: null

  # PVC storage size
  storageSize: 10Gi

  # Seaweed secret name. Override this if you want to use a self-managed secret.
  # Secret must contain the following keys:
  # - s3RootPassword
  secretKeyName: seaweedfs-secret

  # Pod Resource Limits
  resourcesPreset: medium
  resources: null

  # extra volume mounts
  volumes: null
  volumeMounts: null

  # custom secret values
  secret:
    s3RootPassword: null
    mountCredentials: null

proxy:
  # Extra environment vars
  env: null

  # Pod Resource Limits
  resourcesPreset: nano
  resources: null

registry:
  # Extra environment vars
  env: null

  # PVC storage size
  storageSize: 10Gi

  # Pod Resource Limits
  resourcesPreset: nano
  resources: null

node:
  # Syft settings
  name: null
  rootEmail: info@openmined.org
  type: domain
  side: high
  inMemoryWorkers: false
  defaultWorkerPoolCount: 1
  defaultBucketName: null
  queuePort: 5556
  logLevel: info
  debuggerEnabled: false

  # SMTP Settings
  smtp:
    host: smtp.sendgrid.net
    port: 587
    from: noreply@openmined.org
    username: apikey
    password: password

  # Extra environment vars
  env: null

  # Pod Resource Limits
  resourcesPreset: medium
  resources: null

  # Seaweed secret name. Override this if you want to use a self-managed secret.
  # Secret must contain the following keys:
  # - defaultRootPassword
  secretKeyName: backend-secret

  # custom secret values
  secret:
    defaultRootPassword: null

ingress:
  hostname: null # do not make this localhost

  tls:
    enabled: false
    secretName: null

  # ----------------------------------------
  # For Azure
  # className: azure-application-gateway
  # ----------------------------------------
  # For AWS
  # className: alb
  # ----------------------------------------
  # For GCE, https://cloud.google.com/kubernetes-engine/docs/how-to/load-balance-ingress#create-ingress
  # class: gce
  # ----------------------------------------
  class: null
  className: null
