{{- if .Values.veilid.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: veilid
  labels:
    {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: veilid
spec:
  type: ClusterIP
  selector:
    {{- include "common.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: veilid
  ports:
    - name: python-server
      port: 80
      protocol: TCP
      targetPort: 4000
{{ end }}